// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Image is the predicate function for image builders.
type Image func(*sql.Selector)

// Post is the predicate function for post builders.
type Post func(*sql.Selector)

// Profile is the predicate function for profile builders.
type Profile func(*sql.Selector)

// Tag is the predicate function for tag builders.
type Tag func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
